### PR TITLE
Test with vcloud

### PR DESCRIPTION
**Pull request by natb1**
The terremark "vcloud" service (https://github.com/fog/fog-terremark/blob/master/lib/fog/terremark/vcloud.rb) includes important utility methods that aren't in the "vanilla" compute service (https://github.com/fog/fog-terremark/blob/master/lib/fog/compute/terremark.rb). Initializing the terremark compute service the way it is done in the existing test will fail on all requests because it will not include the logic in the vcloud service. ex:
```
describe Fog::Compute::Terremark do
  it 'gets a login token' do
    service = Fog::Compute::Terremark.new(
        :terremark_vcloud_username => 'test@example.com',
        :terremark_vcloud_password => '123456')
    service.send(:auth_token)
  end
end
```
will raise `undefined method `request' for nil:NilClass` (referring to the connection property defined in the vcloud service).

This test reflects usage that will succeed in making requests. Should an additional issue be opened to migrate the vcloud utility methods to the terremark service? (here maybe https://github.com/fog/fog-terremark/blob/master/lib/fog/compute/terremark/common.rb) 

This test also mocks the excon requests.

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@natb1 Are you up to finish this?

**Comment by natb1** [comment]
I'd like to if I can find a minute. I can try to tackle this next week or else close it down.

**Comment by plribeiro3000** [comment]
awesome @natb1! Thank you for your efforts!

**Comment by natb1** [comment]
this branch now passes the hound and travis tests. I don't know exactly how the coveralls test works but it seems to be working under the assumption that the code previously has 100% test coverage (which is not accurate).

**Comment by plribeiro3000** [comment]
Awesome @natb1 ! Thanks!

**Comment by plribeiro3000** [comment]
Do you need a new release with this changes?

**Comment by natb1** [comment]
me? no. release however you see fit

**Comment by plribeiro3000** [comment]
The advantage of having separate gems for each provider is that we can have different versions.
If you would like to have a new version i can release it. This repo isn't that active so i don't think it would be bad to cut a new release for it. =)

**Comment by plribeiro3000** [comment]
Wait, there is just tests here so it does not make sense at all. heheheh
Or did you add something new here?

**Comment by natb1** [comment]
this also resolves an issue that occurs when credentials are longer than 60 characters. (it was necessary to resolve that issue for me to get the vcr results)

**Comment by plribeiro3000** [comment]
So i will do a patch release. =)

**Comment by plribeiro3000** [comment]
@natb1 You should be able to use version `0.0.4`. =)

**Pull request merged**
